---
title: 'Modelling: Cox and LMM'
output:
  html_document: default
  pdf_document: default
date: "`r Sys.Date()`"
---

## Data prep

```{r library and df, results = 'hide'}
setwd("C:/Users/ekaba/0 Uni TUDO/Case Studies/eye_tracking")

library(parameters)
library(dplyr)
library(lme4)
library(ggplot2)
library(clubSandwich)
library(performance)
library(car)
library(colorspace)
library(lmerTest)
library(survival)
library(coxme)
library(survminer)

df <- read.csv("./results/post_processed_data.csv")

# Reorder Age_Group_Cluster such that "5-18" is the first group
df$Age_Group_Cluster <- factor(df$Age_Group_Cluster,
                               levels = c("5-18", "19-26", "27-35", "36-45", "46-59"))

df$Order_sq <- (df$Order)**2
df$Order_standardized <- scale(df$Order)

#df <- df %>%
# filter(duration < 1.5) #test

# Convert the variable to a factor first
df$ROI <- factor(df$ROI)

# Use relevel to set the reference level to "None"
df$ROI <- relevel(df$ROI, ref = "No_ROI")

df$R_norm <- df$red / 255
df$G_norm <- df$green / 255
df$B_norm <- df$blue / 255

# Create a matrix of normalized RGB values
rgb_matrix <- as.matrix(df[, c('R_norm', 'G_norm', 'B_norm')])

# Convert RGB to HSV
hsv_values <- RGB(rgb_matrix) %>% as("HSV") %>% coords()

# Add HSV values to the data frame
df$Hue <- hsv_values[, 1]
df$Saturation <- hsv_values[, 2]
df$Brightness <- hsv_values[, 3]

# Normalize Hue to [0, 1]
df$Hue_norm <- df$Hue / 360

# Standardize predictors
df$Hue_std <- scale(df$Hue_norm)
df$Saturation_std <- scale(df$Saturation)
df$Brightness_std <- scale(df$Brightness)

# Define color categories based on Hue ranges
df$ColorCategory <- cut(
  df$Hue_norm,
  breaks = c(0, 60/360, 120/360, 180/360, 240/360, 300/360, 1),
  labels = c("Red", "Yellow", "Green", "Cyan", "Blue", "Magenta"),
  include.lowest = TRUE
)

# Convert to factor
df$ColorCategory <- factor(df$ColorCategory)

df$age_std <- scale(df$age)

df$event <- 1 # for cox

```

# Cox Regression

```{r cox}
model_1 <- coxph(Surv(duration, event) ~ Order_standardized, data = df)
concordance(model_1)
model_2 <- coxph(Surv(duration, event) ~ Order_standardized + I(Order_standardized^2), data = df)
concordance(model_2)
anova(model_1, model_2)

model_3 <- coxph(Surv(duration, event) ~ Order_standardized + I(Order_standardized^2) + ColorCategory + Brightness_std + Saturation_std, data = df)
concordance(model_3)
anova(model_2, model_3)

model_4 <- coxph(Surv(duration, event) ~ Order_standardized + I(Order_standardized^2) + ROI + ColorCategory + Brightness_std + Saturation_std + ROI, data = df)
concordance(model_4)
anova(model_3, model_4)


model_5 <- coxph(Surv(duration, event) ~ Order_standardized + I(Order_standardized^2) + ROI + ColorCategory + Brightness_std + Saturation_std + Age_Group_Cluster , data = df)
concordance(model_5)
anova(model_4, model_5)

model_final <- coxph(Surv(duration, event) ~ Order_standardized + I(Order_standardized^2) + ROI + ColorCategory + Brightness_std + Saturation_std + Age_Group_Cluster + Gender, data = df)
concordance(model_final)
anova(model_5, model_final)


model_final_int <- coxph(Surv(duration, event) ~ Order_standardized + I(Order_standardized^2) + ROI + ColorCategory + Brightness_std + Saturation_std + Age_Group_Cluster + Gender + Age_Group_Cluster*Order_standardized + Age_Group_Cluster*I(Order_standardized^2), data = df)
vif(model_final_int) # bad


```

# Mixed Effects Cox Model
```{r cox}
model <- coxme(Surv(duration, event) ~ Order_standardized + I(Order_standardized^2) + Age_Group_Cluster + Gender + ROI + ColorCategory + Brightness_std + Saturation_std +  (1 | ID), data = df)

model

# Check proportional hazards assumption
test.ph <- cox.zph(model)
test.ph
ggcoxzph(test.ph)

```
# Age Cox

```{r cox age}
df_5_18 <- subset(df, Age_Group_Cluster == "5-18")
df_19_26 <- subset(df, Age_Group_Cluster == "19-26")
df_27_35 <- subset(df, Age_Group_Cluster == "27-35")
df_36_45 <- subset(df, Age_Group_Cluster == "36-45")
df_46_59 <- subset(df, Age_Group_Cluster == "46-59")

cox_5_18 <- coxme(Surv(duration, event) ~ Order + I(Order_standardized^2) + age_std + Gender + ROI + ColorCategory + Brightness_std + Saturation_std + (1 | ID), data = df_5_18)

cox_19_26 <- coxme(Surv(duration, event) ~ Order + I(Order_standardized^2) + age_std + Gender + ROI + ColorCategory + Brightness_std + Saturation_std + (1 | ID), data = df_19_26)

cox_27_35 <- coxme(Surv(duration, event) ~ Order + I(Order_standardized^2) + age_std + Gender + ROI + ColorCategory + Brightness_std + Saturation_std + (1 | ID), data = df_27_35)

cox_36_45 <- coxme(Surv(duration, event) ~ Order + I(Order_standardized^2) + age_std + Gender + ROI + ColorCategory + Brightness_std + Saturation_std + (1 | ID), data = df_36_45)

cox_46_59 <- coxme(Surv(duration, event) ~ Order + I(Order_standardized^2) + age_std + Gender + ROI + ColorCategory + Brightness_std + Saturation_std + (1 | ID), data = df_46_59)

```

# Functions for plots LMM

```{r functions, echo=FALSE}
plot_residuals <- function(model){
  
  residuals_model <- residuals(model, type = "pearson")
  
  # Plot residuals vs fitted values
  fitted_values <- fitted(model)
  plot(fitted_values, residuals_model, xlab = "Fitted Values", ylab = "Residuals",
       main = "Residuals vs Fitted Values")
  abline(h = 0, col = "red", lty = 2)
  
  # Q-Q plot of residuals
  qqnorm(residuals_model, main = "Q-Q Plot of Residuals")
  qqline(residuals_model, col = "red")
  
  #create histogram of residuals
  hist(residuals_model, xlab = "Residuals", main = "Histogram of the residuals")
  
  predicted_values <- predict(model)
  
  # Create a data frame with actual and predicted values
  plot_data <- data.frame(
    Actual_Log_Duration = df$log_duration,  # Actual log-transformed duration
    Predicted_Log_Duration = predicted_values
  )
  
  min_value <- min(plot_data$Predicted_Log_Duration, plot_data$Actual_Log_Duration)
  max_value <- max(plot_data$Predicted_Log_Duration, plot_data$Actual_Log_Duration)
  
  # Add a trend line to see if there are systematic deviations
  ggplot(plot_data, aes(x = Predicted_Log_Duration, y = Actual_Log_Duration)) +
    geom_point(alpha = 0.5) +
    geom_abline(slope = 1, intercept = 0, color = "red", linetype = "dashed") +
    geom_smooth(method = "lm", color = "blue") +  # Add a smooth trend line
    labs(
      title = "Actual vs. Predicted Log Duration with Trend Line",
      x = "Predicted Log Duration",
      y = "Actual Log Duration"
    ) +
    theme_minimal() +
    coord_fixed(ratio = 1) + # Set the aspect ratio to 1:1
    xlim(min_value, max_value) +  # Set x-axis limits from min to max
    ylim(min_value, max_value)    # Set y-axis limits from min to max
} 

get_robust_se <- function(model, df){
  
  robust_se <- vcovCR(model, cluster = df$ID, type = "CR2")
  summary_robust <- coef_test(model, vcov = robust_se)
  
  print(summary_robust)
}


random_effects_diagnostics <- function(model, effect_name = "a") {
  # Extract all random effects
  random_effects <- ranef(model)

#Check for the random effect column name
  if (!effect_name %in% colnames(random_effects)) {
    stop(paste("Effect", effect_name, "not found. Available effects are:",
               paste(colnames(random_effects), collapse = ", ")))
  }

#Extract the specified random effect
  effect_values <- random_effects[, effect_name]

#Q-Q plot for the random effect
  qqnorm(effect_values, 
         main = paste("Q-Q Plot for Random Effect:", effect_name), 
         pch = 20, col = "blue")
  qqline(effect_values, col = "red", lty = 2)

#Return the random effect values for further use
  return(effect_values)
}

df$Age_Group_Cluster <- as.factor(df$Age_Group_Cluster)
df$Gender <- as.factor(df$Gender)
df$ROI <- as.factor(df$ROI)
df$ID <- as.factor(df$ID)

```

# LMM

```{r models}
# base model
model1<- lmer(log_duration ~ Order_standardized + (1 | ID), data = df)
print(r2(model1))
model2 <- lmer(log_duration ~ Order_standardized  + I(Order_standardized^2) + (1 | ID), data = df)
print(r2(model2))
anova(model1, model2)


model3 <- lmer(log_duration ~ Order_standardized + I(Order_standardized^2) + ColorCategory + Saturation_std + Brightness_std + (1 | ID), data = df)
print(r2(model3))
anova(model2, model3)

model4 <- lmer(log_duration ~ Order_standardized  + I(Order_standardized^2) + ColorCategory + Saturation_std + Brightness_std + ROI + (1 | ID), data = df)
anova(model3, model4)
print(r2(model4))

model5 <- lmer(log_duration ~ Order_standardized  + I(Order_standardized^2) + ColorCategory + Saturation_std + Brightness_std + ROI + Age_Group_Cluster + (1 | ID), data = df)
print(r2(model5))
anova(model4, model5)

modelfinal <- lmer(log_duration ~ Order_standardized  + I(Order_standardized^2) + ColorCategory + Saturation_std + Brightness_std + ROI + Age_Group_Cluster + Gender + (1 | ID), data = df)
print(r2(model5))
anova(model5, modelfinal)

get_robust_se(model5, df)
```



```{r final model plot residuals}
plot_residuals(model5)
vif(model5)
```

# Normality of RE

```{r normality of random effects}
library(checkmate)
library(cowplot)
library(ggplot2)
library(purrr)
library(tidyr)
library(qqplotr)

plot_ranef <- function(model){

  # Return an error if an acceptable model type is not entered in the function
  checkmate::expect_class(model, "lmerMod",
                          info = "The input model is not accepted by plot_raneff. Model must be fit using 'lmer'.")

  # building dataframe of all random effects
  bmat <- as.data.frame(lme4::ranef(model))

  # converting each random effect vector into one line with nest
  renest <- tidyr::nest(bmat, data = c("grp", "condval", "condsd"))

  # generating list of ggplot objects for each random effect vector
  plots <- purrr::pmap(list(renest$data, renest$grpvar, renest$term),
                          function(a,b,c){
                            ggplot(data = a, aes_string(sample = "condval")) +
                              qqplotr::stat_qq_band(bandType = "pointwise",
                                                    distribution = "norm",
                                                    fill = "#FBB4AE", alpha = 0.4) +
                              qqplotr::stat_qq_line(distribution = "norm", colour = "#FBB4AE") +
                              qqplotr::stat_qq_point(distribution = "norm") +
                              xlab("Normal quantiles") + theme_bw() +
                              ylab(paste(b,": ", c)) +
                              ggtitle('Q-Q plot of the random effect') + 
                              theme(plot.title = element_text(hjust = 0.5))
                          }
  )

  # Create grid of all random effect plots
  cowplot::plot_grid(plotlist = plots)
}

plot_ranef(model5)
```
Code from https://rdrr.io/github/goodekat/redres/src/R/plot_ranef.R

# Looking at specific age clusters

```{r other models 3}
# Split the dataset by age group 
df$age_std <- scale(df$age)

df_5_18 <- subset(df, Age_Group_Cluster == "5-18")
df_19_26 <- subset(df, Age_Group_Cluster == "19-26")
df_27_35 <- subset(df, Age_Group_Cluster == "27-35")
df_36_45 <- subset(df, Age_Group_Cluster == "36-45")
df_46_59 <- subset(df, Age_Group_Cluster == "46-59")

# Age Group 5-18
model_5_18 <- lmer(log_duration ~ Order_standardized + I(Order_standardized^2) + age_std +  Gender  + ROI + ColorCategory + Saturation_std + Brightness_std + (1 | ID), data = df_5_18)
# Age Group 19-26
model_19_26 <- lmer(log_duration ~ Order_standardized + I(Order_standardized^2) + age_std + Gender + ROI + ColorCategory + Saturation_std + Brightness_std  + (1 | ID), data = df_19_26)
# Age Group 27-35
model_27_35 <- lmer(log_duration ~ Order_standardized + I(Order_standardized^2) + age_std + Gender + ROI + ColorCategory + Saturation_std + Brightness_std + (1 | ID), data = df_27_35)
# Age Group 36-45
model_36_45 <- lmer(log_duration ~ Order_standardized + I(Order_standardized^2) + age_std + Gender  + ROI + ColorCategory + Saturation_std + Brightness_std  + (1 | ID), data = df_36_45)
# Age Group 46-59
model_46_59 <- lmer(log_duration ~ Order_standardized + I(Order_standardized^2) + age_std + Gender  + ROI + ColorCategory + Saturation_std + Brightness_std  + (1 | ID), data = df_46_59)

get_robust_se(model_5_18, df_5_18)
get_robust_se(model_19_26, df_19_26)
get_robust_se(model_27_35, df_27_35)
get_robust_se(model_36_45, df_36_45)
get_robust_se(model_46_59, df_46_59)

print(r2(model_5_18))
print(r2(model_19_26))
print(r2(model_27_35))
print(r2(model_36_45))
print(r2(model_46_59))


```







